-- MySQL Script generated by MySQL Workbench
-- Wed Aug  4 14:15:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema is1_projekat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema is1_projekat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `is1_projekat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `is1_projekat` ;

-- -----------------------------------------------------
-- Table `is1_projekat`.`pesma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`pesma` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`pesma` (
  `idPesma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPesma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`alarm` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`alarm` (
  `idAlarm` INT NOT NULL,
  `vreme` DATETIME NOT NULL,
  `perioda` INT NULL DEFAULT NULL,
  `zvono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlarm`),
  INDEX `_alarm_pesma_pesma_idPesma_idx` (`zvono` ASC) VISIBLE,
  CONSTRAINT `_alarm_zvono_pesma_idPesma`
    FOREIGN KEY (`zvono`)
    REFERENCES `is1_projekat`.`pesma` (`idPesma`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`lokacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`lokacija` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`lokacija` (
  `idLokacija` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLokacija`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`planer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`planer` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`planer` (
  `idPlaner` INT NOT NULL,
  `idKorisnik` VARCHAR(20) NOT NULL,
  `podsetnik` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPlaner`),
  INDEX `_planer_podsetnik_idx` (`podsetnik` ASC) VISIBLE,
  CONSTRAINT `_planer_podsetnik`
    FOREIGN KEY (`podsetnik`)
    REFERENCES `is1_projekat`.`alarm` (`idAlarm`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`korisnik` (
  `idKorisnik` VARCHAR(20) NOT NULL,
  `kuca` VARCHAR(45) NOT NULL,
  `planer` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idKorisnik`),
  INDEX `_korisnik_kuca_idx` (`kuca` ASC) VISIBLE,
  INDEX `_korisnik_planer_idx` (`planer` ASC) VISIBLE,
  CONSTRAINT `_korisnik_kuca`
    FOREIGN KEY (`kuca`)
    REFERENCES `is1_projekat`.`lokacija` (`idLokacija`)
    ON UPDATE CASCADE,
  CONSTRAINT `_korisnik_planer`
    FOREIGN KEY (`planer`)
    REFERENCES `is1_projekat`.`planer` (`idPlaner`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`korisnik_slusao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`korisnik_slusao` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`korisnik_slusao` (
  `korisnik` VARCHAR(20) NOT NULL,
  `pesma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`korisnik`, `pesma`),
  INDEX `_korisnik_slusao_korisnik_korisnik_idKorsniki_idx` (`pesma` ASC) VISIBLE,
  CONSTRAINT `_korisnik_slusao_korisnik`
    FOREIGN KEY (`korisnik`)
    REFERENCES `is1_projekat`.`korisnik` (`idKorisnik`)
    ON UPDATE CASCADE,
  CONSTRAINT `_korisnik_slusao_pesma`
    FOREIGN KEY (`pesma`)
    REFERENCES `is1_projekat`.`pesma` (`idPesma`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`obaveza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`obaveza` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`obaveza` (
  `idObaveza` VARCHAR(45) NOT NULL,
  `pocetak` DATETIME NOT NULL,
  `trajanje` INT NOT NULL,
  `destnacija` VARCHAR(45) NOT NULL,
  `pocetna_lokacija` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idObaveza`),
  INDEX `_obaveza_destnacija_idx` (`destnacija` ASC) VISIBLE,
  INDEX `_obaveza_destnacija_idx1` (`pocetna_lokacija` ASC) VISIBLE,
  CONSTRAINT `_obaveza_destnacija`
    FOREIGN KEY (`destnacija`)
    REFERENCES `is1_projekat`.`lokacija` (`idLokacija`)
    ON UPDATE CASCADE,
  CONSTRAINT `_obaveza_pocetna_lokacija`
    FOREIGN KEY (`pocetna_lokacija`)
    REFERENCES `is1_projekat`.`lokacija` (`idLokacija`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `is1_projekat`.`praner_obaveza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `is1_projekat`.`praner_obaveza` ;

CREATE TABLE IF NOT EXISTS `is1_projekat`.`praner_obaveza` (
  `planer` INT NOT NULL,
  `obaveza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`planer`, `obaveza`),
  INDEX `_praner_obaveza_obaveza_idx` (`obaveza` ASC) VISIBLE,
  CONSTRAINT `_praner_obaveza_obaveza`
    FOREIGN KEY (`obaveza`)
    REFERENCES `is1_projekat`.`obaveza` (`idObaveza`)
    ON UPDATE CASCADE,
  CONSTRAINT `_praner_obaveza_planer`
    FOREIGN KEY (`planer`)
    REFERENCES `is1_projekat`.`planer` (`idPlaner`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
